add docu for contribution to the ig
music-encoding/metadata-ig pull request #22
Opened 2022-07-12 05:42 UTC by riedde

This is a first draft for the contribution guidelines of the IG. It also documents the actual state of 'how to contribute to music-encoding' which is developed by the technical team and me.

To be discussed in an IG meeting.

2022-08-02 15:03 UTC, doerners requested changes
First of all, many thanks @riedde for this great work. I found some typos and made some suggestions on wording. I think the typos should be addressed before merging.

2022-08-03 07:07 UTC, riedde commented on README.md
> +This is a workspace for the metadata-ig snippets, examples and text blocs can be stored for further development. This is also a place for managing discussions and issues the IG takes care about.
Thank you for this nice suggestion @doerners :)

2022-08-11 10:32 UTC, riedde commented on README.md
> +The workflow to contribute to the schema and guidelines is different to the workflow described above. (see also [https://github.com/orgs/music-encoding/projects/2#card-83741232](https://github.com/or
Thank you, I have improved it.

2022-08-11 12:50 UTC, doerners approved these changes

2022-08-11 12:56 UTC, rettinghaus reviewed
There are still some open suggestions. Please go through them again.

2022-08-11 12:56 UTC, rettinghaus commented on README.md
> +- Diskussions: This should be some kind of 'save place' for everyone (newbies, old hands, etc.) to come up with everything that is on their mind: questions, ideas (that can be very vage), announcemen
@riedde Did you forget to commit this suggestion?

2022-08-11 13:10 UTC, riedde commented on README.md
> +- Diskussions: This should be some kind of 'save place' for everyone (newbies, old hands, etc.) to come up with everything that is on their mind: questions, ideas (that can be very vage), announcemen
sry, this was skipped in the GUI, so I missed it!

2022-08-11 13:16 UTC, riedde commented on README.md
> +- Pushing directly to the directory is not recommented. Please use always the [pull request](https://github.com/music-encoding/metadata-ig/pulls) feature. This makes it easier to manage the code and
@doerners I updated your suggestion (`directory` to `repository`). Not the best way, I know, but easier to fix that right now.

2022-08-11 13:17 UTC, riedde commented
Thank you @rettinghaus for taking care of what I'm doing! :) I resolved the open requests.

2022-08-11 13:41 UTC, rettinghaus approved these changes
Thank you. 
@doerners Please have a final look and merge.

2022-08-14 10:09 UTC, doerners commented
Thanks @riedde and @rettinghaus! Looks good to me, merging this now.

2022-08-14 10:09 UTC, merged